#!/bin/sh
set -e

echo "🚀 Starting application setup..."

# 1. Tunggu MariaDB (Wajib agar tidak crash di awal)
echo "⏳ Waiting for MariaDB..."
while ! php -r "\$c = @new mysqli('${DB_HOST:-db}', '${DB_USER:-root}', '${DB_PASS:-secret}'); if(\$c->connect_error) exit(1);" 2>/dev/null; do
    sleep 2
done
echo "✅ MariaDB is ready!"

# 2. Opsional: Backup config lama & buat yang baru dari Env Docker
# Ini menjamin aplikasi selalu pakai host 'db' dan bukan 'localhost'
CONFIG_FILE="/var/www/html/includes/config.php"
echo "📝 Refreshing config.php for production..."
cat > "$CONFIG_FILE" <<PHPEOF
<?php
// Generated by Docker Entrypoint
if (session_status() === PHP_SESSION_NONE) { session_start(); }
date_default_timezone_set('Asia/Jakarta');

\$host = '${DB_HOST:-db}';
\$user = '${DB_USER:-root}';
\$pass = '${DB_PASS:-secret}';
\$dbname = '${DB_NAME:-kasir_toko}';

\$conn = new mysqli(\$host, \$user, \$pass, \$dbname);
if (\$conn->connect_error) { die("Koneksi gagal: " . \$conn->connect_error); }

\$root = '${APP_URL:-http://localhost}/';
PHPEOF

echo "🎉 Application ready!"
exec "$@"